OnlineHouse/OnlineHouse/Controllers/RenterHomeController.cs
using OnlineHouse.App_Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineHouse.Controllers
{
    public class RenterHomeController : Controller
    {
        private HouseManageDb context = new HouseManageDb();
        // GET: RenterHome
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FilterHouse()
        {
            var model = context.Houses.SqlQuery("select * from House where Status = 'True' ").ToList<House>();
            return View(model);
        }

        public ActionResult FilterRoom(string id)
        {
            Session["HouseName"] = context.Houses.SqlQuery("select * from House where HouseID = '" + id + "'").First<House>().HouseName.ToString();

            var model = context.Rooms.SqlQuery("select * from Room where HouseID = '" + id + "'").ToList<Room>();
            return View(model);
        }
        [HttpPost]
        public ActionResult chooseRoom(string id)
        {
            Inform inform = new Inform();
            inform.RoomID = id;
            inform.UserID = Session["UserID"].ToString();
            inform.NameRenter = "Tường";
            //inform.NameRenter = Session["Name"].ToString();
            inform.HouseName = Session["HouseName"].ToString();
            //  Time
            context.Informs.Add(inform);
            context.SaveChanges();
            string message = "SUCCESS";
            return Json(new { Message = message , JsonRequestBehavior.AllowGet});
        }
    }
}

OnlineHouse/OnlineHouse/Views/RenterHome/FilterHouse.cshtml
@{
    ViewBag.Title = "FilterHouse";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>The Apartments Have a Vacant Rooms...</h3>
<div id="showRom">
    <div id="reloadView" class="row">
        @foreach (var item in Model)
        {
            <a href="@Url.Action("FilterRoom","RenterHome", new {id = @item.HouseID})">

                <!-- Earnings (Monthly) Card Example -->
                <div class="col-xl-3 col-md-6 mb-4" id="row_@item.ID">

                    <div class="card border-left-primary shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">@item.HouseName</div>
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">@item.Address</div>
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">@item.NumberOfRoom</div>
                                    <a></a>
                                </div>

                                <div class="col-mr-2">

                                    <i class="fas fa-home fa-2x text-gray-300"></i>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>

            </a>
        }

    </div>
</div>

OnlineHouse/OnlineHouse/Views/RenterHome/FilterRoom.cshtml
@{
    ViewBag.Title = "FilterRoom";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h3>The Vacant Rooms of  @Session["HouseName"]</h3>
<div class="row">
    @foreach (var item in Model)
    {
        <a href="/" onclick="return false" id="@item.RoomID" class="blockBox">
            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-2 col-md-6 mb-4" id="row_@item.ID">

                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Tên Phòng @item.Renter </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">@item.Capacity/3</div>
                                <a></a>
                            </div>

                            <div class="col-mr-2">

                                <i class="fas fa-home fa-2x text-gray-300"></i>
                            </div>
                            <div class="col-mr-8">

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </a>

    }

</div>
<script>
    $(".blockBox").click(function () {
        confirm('Do You Really Rent This Room ???');
        var id = $(this).attr("id");
        alert(id);
        $.ajax({
            type: "POST",
            url: "@Url.Action("chooseRoom")",
            data: { id: id },
            success: function () {
                alert("The require was sent. Please wait for the owner's response...");

            },
            error: function () {
                alert("Error. Can't sent request !!!");
            }
        })


    });
</script>

OnlineHouse/OnlineHouse/Views/RenterHome/Index.cshtml
@{
    ViewBag.Title = "My Room";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>My Room</h2>

<div style="text-align:center;margin-top:25%">
    <a href="/RenterHome/FilterHouse" class="btn btn-primary" id="filter"  style="font-size: 30px;">You have not the room yet. Let us help to find for you...!!!</a>

</div>